### ISSUE TITLE
vertx-grpc is causing UnsupportedOperation exception on 4.5.1

### ISSUE THREAD

**Issue by afabris-kodypay** [vert-x3/vertx-grpc#143]
### Version

Vertx 4.5.1

### Context
In my project I've extended StreamObserver (from base grpc) to implement a testing class.
This class is then being used in our ITs to perform grpc calls to a vertx server spawned locally through VertxExtension
Our server is using the new grpc-server module.
However our test class is creating a Channel using VertxChannelBuilder from vertx-grpc.
Since we updated to vertx 4.5.1 we've noticed stack traces like below
```
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:537) ~[grpc-api-1.59.0.jar:1.59.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:491) ~[grpc-stub-1.57.2.jar:1.57.2]
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:471) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:435) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:468) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.vertx.grpc.VertxChannelBuilder.lambda$null$0(VertxChannelBuilder.java:305) ~[vertx-grpc-4.5.1.jar:4.5.1]
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:276) ~[vertx-core-4.5.1.jar:4.5.1]
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:258) ~[vertx-core-4.5.1.jar:4.5.1]
	at io.vertx.grpc.VertxChannelBuilder.lambda$build$1(VertxChannelBuilder.java:305) ~[vertx-grpc-4.5.1.jar:4.5.1]
	at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:102) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:95) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closedInternal(ClientCallImpl.java:752) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:688) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.RetriableStream$Sublistener$5.run(RetriableStream.java:986) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94) ~[grpc-api-1.59.0.jar:1.59.0]
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126) ~[grpc-api-1.59.0.jar:1.59.0]
	at io.grpc.internal.RetriableStream$Sublistener.closed(RetriableStream.java:981) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.DelayedStream$DelayedStreamListener$4.run(DelayedStream.java:510) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.DelayedStream$DelayedStreamListener.delayOrExecute(DelayedStream.java:462) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.DelayedStream$DelayedStreamListener.closed(DelayedStream.java:507) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.ForwardingClientStreamListener.closed(ForwardingClientStreamListener.java:34) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.InternalSubchannel$CallTracingTransport$1$1.closed(InternalSubchannel.java:693) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.AbstractClientStream$TransportState.closeListener(AbstractClientStream.java:458) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.AbstractClientStream$TransportState.access$400(AbstractClientStream.java:221) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.AbstractClientStream$TransportState$1.run(AbstractClientStream.java:441) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.AbstractClientStream$TransportState.deframerClosed(AbstractClientStream.java:278) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.Http2ClientStreamTransportState.deframerClosed(Http2ClientStreamTransportState.java:31) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:234) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.MessageDeframer.closeWhenComplete(MessageDeframer.java:192) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:200) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.AbstractClientStream$TransportState.transportReportStatus(AbstractClientStream.java:444) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.internal.AbstractClientStream$TransportState.transportReportStatus(AbstractClientStream.java:400) ~[grpc-core-1.50.2.jar:1.50.2]
	at io.grpc.netty.NettyClientHandler$3.visit(NettyClientHandler.java:446) ~[grpc-netty-1.50.2.jar:1.50.2]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.forEachActiveStream(DefaultHttp2Connection.java:978) ~[netty-codec-http2-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.http2.DefaultHttp2Connection.forEachActiveStream(DefaultHttp2Connection.java:209) ~[netty-codec-http2-4.1.103.Final.jar:4.1.103.Final]
	at io.grpc.netty.NettyClientHandler.channelInactive(NettyClientHandler.java:441) ~[grpc-netty-1.50.2.jar:1.50.2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.103.Final.jar:4.1.103.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.UnsupportedOperationException
	at io.grpc.netty.AbstractHttp2Headers.iterator(AbstractHttp2Headers.java:500) ~[grpc-netty-1.50.2.jar:1.50.2]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:425) ~[netty-codec-http2-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:65) ~[netty-codec-http2-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$1.processFragment(DefaultHttp2FrameReader.java:450) ~[netty-codec-http2-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:457) ~[netty-codec-http2-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:253) ~[netty-codec-http2-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159) ~[netty-codec-http2-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41) ~[netty-codec-http2-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:188) ~[netty-codec-http2-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393) ~[netty-codec-http2-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453) ~[netty-codec-http2-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
	... 4 more
```
The problem is caused by vertx-grpc using grpc-netty 1.50 that doesn't implement iterator that is being used, instead, by netty 4.1.103
The issue is fixed if we include explicitly grpc-netty 1.59.1 in the dependencies list

### Extra

Using JDK 21, Kotlin 1.9.22

**Comment by vietj** [comment]
what is the version of the grpc-netty library you are using ?

**Comment by afabris-kodypay** [comment]
The one included in vertx-grpc POM (1.50.2). Forcing it to 1.59.1 resolves the issue,
I can further confirm that grpc-netty 1.50.2 doesn't implement AbstractHttp2Headers.iterator that looks like is being used by Netty 4.1.103 engine.

**Comment by vietj** [comment]
thanks @afabris-kodypay I think we should bump the grpc-netty version in this project to solve this issue

**Comment by afabris-kodypay** [comment]
> > I think we should bump the grpc-netty version in this project to solve this issue
> 
> Seems like it is resolved, branch 4.x have update grpc-netty to 1.61.0
> 
> https://github.com/vert-x3/vertx-grpc/blob/855273d09f7b514262d9a10558ac86d60fa0ad44/vertx-grpc/pom.xml#L33
> 
> So this issue can be closed?
> 
> @vietj A other question: what's different between https://github.com/eclipse-vertx/vertx-grpc/tree/4.x and https://github.com/vert-x3/vertx-grpc/tree/4.x, seems like there are both active.

Oh yes, this can be closed now.
To answer your question: vertx-grpc is the new "Tech Preview" version of GRPC integration [Vert.x gRPC](https://vertx.io/docs/vertx-grpc/java/) while the other is [gRPC Netty](https://vertx.io/docs/vertx-grpc-netty/java/)

**Comment by vietj** [comment]
@liangyuanpeng vert-x3/vertx-grpc will be dropped after 4.0 and eclipse-vertx/vertx-grpc is the new project to use based on the Vert.x HTTP/2 stack
