### ISSUE TITLE
Force com.google.guava:guava 19.0

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-grpc#29]

**Comment by vietj** [comment]
we can't force 19.0

```
Running io.vertx.ext.grpc.GoogleTest
Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.642 sec <<< FAILURE! - in io.vertx.ext.grpc.GoogleTest
streamingInputCallTest(io.vertx.ext.grpc.GoogleTest)  Time elapsed: 0.465 sec  <<< ERROR!
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
	at io.grpc.Metadata$Key.validateName(Metadata.java:628)
	at io.grpc.Metadata$Key.<init>(Metadata.java:636)
	at io.grpc.Metadata$Key.<init>(Metadata.java:566)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:740)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:735)
	at io.grpc.Metadata$Key.of(Metadata.java:592)
	at io.grpc.Metadata$Key.of(Metadata.java:588)
	at io.grpc.internal.GrpcUtil.<clinit>(GrpcUtil.java:83)
	at io.grpc.internal.AbstractServerImplBuilder.<clinit>(AbstractServerImplBuilder.java:58)
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:62)
	at io.vertx.ext.grpc.GoogleTest.streamingInputCallTest(GoogleTest.java:141)

unimplementedCallTest(io.vertx.ext.grpc.GoogleTest)  Time elapsed: 0.009 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:62)
	at io.vertx.ext.grpc.GoogleTest.unimplementedCallTest(GoogleTest.java:309)

emptyUnaryTest(io.vertx.ext.grpc.GoogleTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:62)
	at io.vertx.ext.grpc.GoogleTest.emptyUnaryTest(GoogleTest.java:70)

streamingOutputCallTest(io.vertx.ext.grpc.GoogleTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:62)
	at io.vertx.ext.grpc.GoogleTest.streamingOutputCallTest(GoogleTest.java:99)

emptyCallTest(io.vertx.ext.grpc.GoogleTest)  Time elapsed: 0.009 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:62)
	at io.vertx.ext.grpc.GoogleTest.emptyCallTest(GoogleTest.java:42)

fullDuplexCallTest(io.vertx.ext.grpc.GoogleTest)  Time elapsed: 0.127 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:62)
	at io.vertx.ext.grpc.GoogleTest.fullDuplexCallTest(GoogleTest.java:192)

halfDuplexCallTest(io.vertx.ext.grpc.GoogleTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:62)
	at io.vertx.ext.grpc.GoogleTest.halfDuplexCallTest(GoogleTest.java:247)

Running io.vertx.ext.grpc.VerticleTest
Jun 08, 2018 9:02:35 PM io.vertx.core.impl.DeploymentManager
SEVERE: Failure in calling handler
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.VerticleTest$GrpcVerticle.start(VerticleTest.java:70)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Jun 08, 2018 9:02:35 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.VerticleTest$GrpcVerticle.start(VerticleTest.java:70)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Jun 08, 2018 9:02:35 PM io.vertx.core.impl.DeploymentManager
SEVERE: Failure in calling handler
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.VerticleTest$GrpcVerticle.start(VerticleTest.java:70)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Jun 08, 2018 9:02:35 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.VerticleTest$GrpcVerticle.start(VerticleTest.java:70)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.06 sec <<< FAILURE! - in io.vertx.ext.grpc.VerticleTest
testCloseInVerticle(io.vertx.ext.grpc.VerticleTest)  Time elapsed: 0.04 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.VerticleTest$GrpcVerticle.start(VerticleTest.java:70)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

testBilto(io.vertx.ext.grpc.VerticleTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.VerticleTest$GrpcVerticle.start(VerticleTest.java:70)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

testScaleVerticle(io.vertx.ext.grpc.VerticleTest)  Time elapsed: 0.009 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.VerticleTest$GrpcVerticle.start(VerticleTest.java:70)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Running io.vertx.ext.grpc.RpcTest
Jun 08, 2018 9:02:35 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:62)
	at io.vertx.ext.grpc.RpcTest.lambda$testSimple$1(RpcTest.java:32)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 10.043 sec <<< FAILURE! - in io.vertx.ext.grpc.RpcTest
testStreamPipe(io.vertx.ext.grpc.RpcTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:62)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:51)
	at io.vertx.ext.grpc.RpcTest.testStreamPipe(RpcTest.java:259)

testStreamSink(io.vertx.ext.grpc.RpcTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:62)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:51)
	at io.vertx.ext.grpc.RpcTest.testStreamSink(RpcTest.java:214)

testBlockingException(io.vertx.ext.grpc.RpcTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
	at io.grpc.Metadata$Key.validateName(Metadata.java:628)
	at io.grpc.Metadata$Key.<init>(Metadata.java:636)
	at io.grpc.Metadata$Key.<init>(Metadata.java:566)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:740)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:735)
	at io.grpc.Metadata$Key.of(Metadata.java:592)
	at io.grpc.Metadata$Key.of(Metadata.java:588)
	at io.vertx.ext.grpc.RpcTest.testBlockingException(RpcTest.java:131)

testRandomPort(io.vertx.ext.grpc.RpcTest)  Time elapsed: 0.018 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:62)
	at io.vertx.ext.grpc.RpcTest.testRandomPort(RpcTest.java:301)

testStreamSource(io.vertx.ext.grpc.RpcTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:62)
	at io.vertx.ext.grpc.GrpcTestBase.startServer(GrpcTestBase.java:51)
	at io.vertx.ext.grpc.RpcTest.testStreamSource(RpcTest.java:182)

testBlocking(io.vertx.ext.grpc.RpcTest)  Time elapsed: 0.006 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.RpcTest.testBlocking(RpcTest.java:93)

testSimple(io.vertx.ext.grpc.RpcTest)  Time elapsed: 10.009 sec  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out
	at io.vertx.ext.unit.impl.CompletionImpl.awaitSuccess(CompletionImpl.java:99)
	at io.vertx.ext.grpc.RpcTest.testSimple(RpcTest.java:46)

Running io.vertx.ext.grpc.SslTest
Jun 08, 2018 9:02:45 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.SslTest.lambda$testSimple$9(SslTest.java:109)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Jun 08, 2018 9:02:55 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.SslTest.lambda$testSimple$9(SslTest.java:109)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Jun 08, 2018 9:03:05 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.SslTest.lambda$testSimple$9(SslTest.java:109)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Jun 08, 2018 9:03:15 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyServerBuilder
	at io.vertx.grpc.VertxServerBuilder.<init>(VertxServerBuilder.java:43)
	at io.vertx.grpc.VertxServerBuilder.forPort(VertxServerBuilder.java:24)
	at io.vertx.ext.grpc.SslTest.lambda$testSimple$9(SslTest.java:109)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 40.047 sec <<< FAILURE! - in io.vertx.ext.grpc.SslTest
testTrustAll(io.vertx.ext.grpc.SslTest)  Time elapsed: 10.006 sec  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out
	at io.vertx.ext.unit.impl.CompletionImpl.awaitSuccess(CompletionImpl.java:99)
	at io.vertx.ext.grpc.SslTest.testSimple(SslTest.java:119)
	at io.vertx.ext.grpc.SslTest.testTrustAll(SslTest.java:41)

testClientAuthFail(io.vertx.ext.grpc.SslTest)  Time elapsed: 10.015 sec  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out
	at io.vertx.ext.unit.impl.CompletionImpl.awaitSuccess(CompletionImpl.java:99)
	at io.vertx.ext.grpc.SslTest.testSimple(SslTest.java:119)
	at io.vertx.ext.grpc.SslTest.testClientAuthFail(SslTest.java:77)

testClientAuth(io.vertx.ext.grpc.SslTest)  Time elapsed: 10.014 sec  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out
	at io.vertx.ext.unit.impl.CompletionImpl.awaitSuccess(CompletionImpl.java:99)
	at io.vertx.ext.grpc.SslTest.testSimple(SslTest.java:119)
	at io.vertx.ext.grpc.SslTest.testClientAuth(SslTest.java:55)

testConnect(io.vertx.ext.grpc.SslTest)  Time elapsed: 10.011 sec  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out
	at io.vertx.ext.unit.impl.CompletionImpl.awaitSuccess(CompletionImpl.java:99)
	at io.vertx.ext.grpc.SslTest.testSimple(SslTest.java:119)
	at io.vertx.ext.grpc.SslTest.testConnect(SslTest.java:26)
```

**Comment by vietj** [comment]
@cescoffier it looks like we have to use Guava 20.0 for gRPC - https://github.com/grpc/grpc-java/issues/4176
