### ISSUE TITLE
Hang on shutdown

### ISSUE THREAD

**Issue by avgustinmm** [vert-x3/vertx-grpc#57]
### Version
Vertx: 3.8.4
Netty: 4.1.44.Final
gRPC: 1.26.0
Linux, Alpine
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (IcedTea 3.8.0) (Alpine 8.171.11-r0)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

### Context
We found two hanged event loop threads in our logs. It seems that gRPC server shutdown use to block the thread the shutdown is called into and wait for channel to close. Furthermore, I suppose that the close of the channel is waiting to do something into exactly the same event loop thread. 

The thread is:
>[2020-Jan-13 16:52:26.544 UTC] [] [] [io.vertx.core.impl.BlockedThreadChecker] WARN  Thread Thread[vert.x-eventloop-thread-0,10,main]=Thread[vert.x-eventloop-thread-0,10,main] has been blocked for 610568 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at java.lang.Object.wait(Native Method) ~[?:1.8.0_171]
	at java.lang.Object.wait(Object.java:502) ~[?:1.8.0_171]
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:252) ~[?:?]
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131) ~[?:?]
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30) ~[?:?]
	at io.grpc.netty.NettyServer.shutdown(NettyServer.java:298) ~[?:?]
	at io.grpc.internal.ServerImpl.shutdown(ServerImpl.java:273) ~[?:?]
	at io.grpc.internal.ServerImpl.shutdown(ServerImpl.java:90) ~[?:?]
	at io.vertx.grpc.VertxServer$ActualServer.lambda$stop$4(VertxServer.java:108) ~[?:?]
	at io.vertx.grpc.VertxServer$ActualServer$$Lambda$1030/2059682670.handle(Unknown Source) ~[?:?]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[?:?]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[?:?]
	at io.vertx.core.impl.EventLoopContext$$Lambda$35/1779871850.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_171]
>
### Do you have a reproducer?
I don't have any reproducer. It happen just once and I'm not sure for exact conditions. But suppose this is race condition and/or something specific to setup (e.g. OS).

### Extra
Attaching thread dump 
[dev_threaddump.txt](https://github.com/vert-x3/vertx-grpc/files/4064244/dev_threaddump.txt)
Probably shutdown shall be run in blocking thread as it is made with start

**Comment by avgustinmm** [comment]
Do you have any plans to investigate/fix this?

**Comment by vietj** [comment]
we scheduled it for 3.9.1 and will do best effort to fix it

**Comment by avgustinmm** [comment]
Thanks

**Comment by cescoffier** [comment]
@avgustinmm could you provide a reproducer? I believe I've already worked around this issue in Quarkus but I want to be sure that the same "fix" would work in your case.

**Comment by avgustinmm** [comment]
@cescoffier, I tried to make an reproducer but didn't succeed. In fact we had this problem occurred just once. The thread dump is the only info we have regarding the problem

**Comment by vietj** [comment]
it seems that server shutdown is potentially blocking, so we should wrap the NettyServer shutdown in an execute blocking block, I'll do that soon.

**Comment by vietj** [comment]
https://github.com/vert-x3/vertx-grpc/issues/67
